import galleryManifest from "@/data/gallery-manifest.json";

/**
 * The real gallery content: 4 flat sections (no sub-sections, no per-item
 * filtering). Images now live in Vercel Blob rather than public/photos/ —
 * data/gallery-manifest.json is generated by scripts/upload-gallery-images.ts
 * (run manually, not part of the build) and maps each category to its
 * uploaded blob URLs + real pixel dimensions.
 */
export interface GalleryPhoto {
  id: string;
  src: string;
  width: number;
  height: number;
}

export interface PhotoSection {
  id: string;
  title: string;
  images: GalleryPhoto[];
}

interface ManifestImage {
  url: string;
  width: number;
  height: number;
  filename: string;
}

// The manifest itself is just { category: [...] } — flat filenames and
// URLs, no display title — so the human-facing section titles (used by
// the section tabs) are kept here rather than duplicated into generated
// data. SECTION_ORDER also fixes the tab order, since object key order
// isn't a contract worth relying on for that.
const SECTION_TITLES: Record<string, string> = {
  chaos_creative: "Chaos & Creative",
  drawings: "Drawings",
  food: "Food",
  memories: "Memories",
};
const SECTION_ORDER = ["chaos_creative", "drawings", "food", "memories"];

const manifest = galleryManifest as Record<string, ManifestImage[]>;

export const PHOTO_SECTIONS: PhotoSection[] = SECTION_ORDER.map((id) => ({
  id,
  title: SECTION_TITLES[id] ?? id,
  images: (manifest[id] ?? []).map((image) => ({
    id: `${id}-${image.filename}`,
    src: image.url,
    width: image.width,
    height: image.height,
  })),
}));

/**
 * Requested pixel width for grid thumbnails vs. the focused detail view —
 * see getOptimizedSrc below for why these need to land on a width Next's
 * image optimizer already allows. Both are existing entries in Next's
 * default images.imageSizes/deviceSizes, chosen instead of adding a custom
 * width so this doesn't touch the global image-size config that
 * gallery-wall.tsx's next/image usage also depends on.
 */
export const GRID_THUMBNAIL_WIDTH = 256;
export const DETAIL_VIEW_WIDTH = 1200;

/**
 * There's no next/image component inside an R3F scene — the gallery tiles
 * are texture-mapped WebGL mesh planes (see gallery-tile.tsx's useTexture
 * call), not DOM <img> elements, so next/image's `sizes`/srcset mechanism
 * has nothing to attach to here. This gets the same practical result
 * (Vercel's optimizer generates + caches an appropriately-sized variant
 * per request) by calling Next's own image-optimization route directly —
 * exactly what <Image> does under the hood — and feeding the resulting
 * same-origin URL to the texture loader instead of the raw Blob URL.
 */
export function getOptimizedSrc(
  src: string,
  width: number,
  quality = 75,
): string {
  return `/_next/image?url=${encodeURIComponent(src)}&w=${width}&q=${quality}`;
}
